### ISSUE TITLE
https://github.com/silviatofana/Capstone-JavaScript-/projects/1

### ISSUE THREAD

**Issue by silviatofana** [silviatofana/Capstone-JavaScript-#21]
https://github.com/silviatofana/Capstone-JavaScript-/projects/1

**Comment by Abdo9826** [comment]
set up capstone Js as a team

**Comment by mikethreels** [comment]
Hi team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] it is good that you both commented on the issue, however, I advise you to put the number of team members in the comments to avoid misunderstandings.
- [ ] every card should be assigned to a team member which will look something like the following example.
<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/39240820/174575210-40f2b2a0-7c54-488b-b2fe-108277e972b9.png">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by silviatofana** [comment]
did you see the reviewer ask for
1:02
<https://microverse-students.slack.com/archives/C03L9788E9Y/p1655719330434819>
I think you need to do again the cards with yours name on and detele those
are done by myself but with your name on like student b


În lun., 20 iun. 2022 la 11:26, Abdelrahman Mohamed <
***@***.***> a scris:

**Comment by silviatofana** [comment]
@mikethreels thanks for helpful advice please check again my partner redo the cards with his task need to do in the project

**Comment by dasileker** [comment]
### **Hi @silviatofana,** 

### **Great work on making the changes 👏** 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## **Suggested changes**
_Check the comments under the review._

- Please, as the previous CR said, the cards should be attributed to the team and we should see the student's Icon on that card.
- **Your card**
![Capture web_20-6-2022_135730_github com](https://user-images.githubusercontent.com/61562626/174607008-714105d8-b7aa-451b-834b-ada157288719.jpeg)


- **Wanted cards look like**

![Capture web_20-6-2022_135518_github com](https://user-images.githubusercontent.com/61562626/174606629-f056df92-c5c1-4f5d-b70a-e2a04533d391.jpeg)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by silviatofana** [comment]
ok, thanks for helpful advice

**Comment by Lameck1** [comment]
Hi, Team,

You've done well working on the concerns from the previous reviews 👏🏼,
Your Kanban board is now properly set 💯.

### Highlights:
- You've properly assigned yourselves tasks ✔️
- Task distribution is fair ✔️

All the best with the next project.

You are free to merge this branch :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**Please, remember to tag me in your question so I can receive the notification.**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by silviatofana** [comment]
wow thanks God finally
